<a href="https://colab.research.google.com/github/dezurnyjkipia4/DataScince/blob/main/HW3/HW3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# Установка библиотек
!pip install openpyxl
!pip install pyyaml
!pip install pyarrow
import pandas as pd

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (6.0.3)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)

In [53]:
data = pd.read_csv("mercedes_benz_stock_refined.csv")
data.head() # посмотрим на данные

,Date,Open,High,Low,Price,Volume,Daily_Return,Price_Change,Price_Range,MA_7,MA_30,MA_90,Volatility_30,Day_of_Week,Month,Year,Quarter
0,1996-10-30,9.97,9.97,9.88,9.89,1640521,NaN,-0.08,0.09,9.89,9.89,9.89,NaN,Wednesday,10,1996,4
1,1996-10-31,9.91,10.02,9.91,10.02,1908031,1.34,0.11,0.11,9.95,9.95,9.95,NaN,Thursday,10,1996,4
2,1996-11-01,10.08,10.17,10.03,10.07,2423211,0.47,-0.01,0.14,9.99,9.99,9.99,0.61,Friday,11,1996,4
3,1996-11-04,10.08,10.17,10.08,10.14,1284644,0.78,0.07,0.09,10.03,10.03,10.03,0.44,Monday,11,1996,4
4,1996-11-05,10.19,10.34,10.14,10.34,2105206,1.88,0.15,0.20,10.09,10.09,10.09,0.62,Tuesday,11,1996,4

In [54]:
import sqlite3
import pandas as pd

# Подключение к базе данных SQLite
conn = sqlite3.connect('example.db')
cursor = conn.cursor()

# Запрос данных из таблицы statistic
cursor.execute("SELECT * FROM statistic")

# Получение всех строк
rows = cursor.fetchall()

# Вывод данных
if rows:
    # Получение названий столбцов
    col_names = [description[0] for description in cursor.description]
    # Создание DataFrame для удобного просмотра
    df_statistic = pd.DataFrame(rows, columns=col_names)
    print("Данные из таблицы 'statistic':")
    print(df_statistic)
else:
    print("Таблица 'statistic' пуста или данные не были импортированы.")

# Закрытие соединения
conn.close()

Данные из таблицы 'statistic':
            Data  Year Day_of_Week  Daily_Return
0     1996-10-30  1996   Wednesday           NaN
1     1996-10-31  1996    Thursday          1.34
2     1996-11-01  1996      Friday          0.47
3     1996-11-04  1996      Monday          0.78
4     1996-11-05  1996     Tuesday          1.88
...          ...   ...         ...           ...
7335  2026-01-26  2026      Monday         -0.65
7336  2026-01-27  2026     Tuesday         -1.71
7337  2026-01-28  2026   Wednesday          0.84
7338  2026-01-29  2026    Thursday         -0.19
7339  2026-01-30  2026      Friday          0.86

[7340 rows x 4 columns]

In [55]:
#Напишите несколько SQL-запросов для извлечения данных из таблиц базы данных.
#Используйте условия фильтрации (например, WHERE) для получения нужных данных.
import sqlite3
import pandas as pd

# Подключение к базе данных SQLite
conn = sqlite3.connect('example.db')

print("Данные за все время:")
# Запрос всех данных из таблицы statistic
df_all = pd.read_sql_query("SELECT * FROM statistic LIMIT 10", conn)
display(df_all)

print("\nДанные за 2025 год:")
# Запрос данных за конкретный год (например, 2020)
df_2025 = pd.read_sql_query("SELECT * FROM statistic WHERE Year = 2025 LIMIT 10", conn)
display(df_2025)

print("\nДанные только по понедельникам:")
# Запрос данных по конкретному дню недели (например, понедельник)
df_monday = pd.read_sql_query("SELECT * FROM statistic WHERE Day_of_Week = 'Monday' LIMIT 10", conn)
display(df_monday)

print("\nДанные за 2022 год с положительным сальдо:")
# Запрос данных за 2022 год с положительным сальдо
df_2022_positive = pd.read_sql_query("SELECT * FROM statistic WHERE Year = 2022 AND Daily_Return > 0 LIMIT 10", conn)
display(df_2022_positive)

# Закрытие соединения
conn.close()

Данные за все время:

         Data  Year Day_of_Week  Daily_Return
0  1996-10-30  1996   Wednesday           NaN
1  1996-10-31  1996    Thursday          1.34
2  1996-11-01  1996      Friday          0.47
3  1996-11-04  1996      Monday          0.78
4  1996-11-05  1996     Tuesday          1.88
5  1996-11-06  1996   Wednesday          1.53
6  1996-11-07  1996    Thursday         -0.54
7  1996-11-08  1996      Friday          0.38
8  1996-11-11  1996      Monday          0.45
9  1996-11-12  1996     Tuesday          2.27

Данные за 2025 год:

         Data  Year Day_of_Week  Daily_Return
0  2025-01-02  2025    Thursday         -1.71
1  2025-01-03  2025      Friday         -0.81
2  2025-01-06  2025      Monday          3.60
3  2025-01-07  2025     Tuesday         -0.04
4  2025-01-08  2025   Wednesday         -1.86
5  2025-01-09  2025    Thursday         -0.47
6  2025-01-10  2025      Friday          3.73
7  2025-01-13  2025      Monday          0.74
8  2025-01-14  2025     Tuesday          0.18
9  2025-01-15  2025   Wednesday          1.35

Данные только по понедельникам:

         Data  Year Day_of_Week  Daily_Return
0  1996-11-04  1996      Monday          0.78
1  1996-11-11  1996      Monday          0.45
2  1996-11-18  1996      Monday         -1.11
3  1996-11-25  1996      Monday          1.90
4  1996-12-02  1996      Monday          0.89
5  1996-12-09  1996      Monday          2.10
6  1996-12-16  1996      Monday          2.16
7  1996-12-23  1996      Monday          0.20
8  1996-12-30  1996      Monday          2.07
9  1997-01-06  1997      Monday          3.31

Данные за 2022 год с положительным сальдо:

         Data  Year Day_of_Week  Daily_Return
0  2022-01-03  2022      Monday          1.64
1  2022-01-04  2022     Tuesday          4.96
2  2022-01-05  2022   Wednesday          4.01
3  2022-01-12  2022   Wednesday          1.21
4  2022-01-13  2022    Thursday          2.74
5  2022-01-18  2022     Tuesday          0.51
6  2022-01-25  2022     Tuesday          0.76
7  2022-01-26  2022   Wednesday          2.46
8  2022-01-27  2022    Thursday          0.91
9  2022-01-31  2022      Monday          0.09

In [56]:
#Напишите SQL-запросы, использующие агрегатные функции (SUM, AVG, COUNT)
#для выполнения расчетов по данным таблицы.
import sqlite3
import pandas as pd

# Подключение к базе данных SQLite
conn = sqlite3.connect('example.db')

print("Общее количество записей:")
df_count = pd.read_sql_query("SELECT COUNT(*) FROM statistic", conn)
display(df_count)

print("\nСредняя дневная доходность:")
df_avg_daily_return = pd.read_sql_query("SELECT AVG(Daily_Return) FROM statistic", conn)
display(df_avg_daily_return)

print("\nСумма дневной доходности за 2022 год:")
df_sum_2022 = pd.read_sql_query("SELECT SUM(Daily_Return) FROM statistic WHERE Year = 2022", conn)
display(df_sum_2022)

print("\nКоличество дней с положительной доходностью:")
df_positive_days = pd.read_sql_query("SELECT COUNT(*) FROM statistic WHERE Daily_Return > 0", conn)
display(df_positive_days)

print("\nСредняя дневная доходность по годам:")
df_avg_by_year = pd.read_sql_query("SELECT Year, AVG(Daily_Return) FROM statistic GROUP BY Year ORDER BY Year", conn)
display(df_avg_by_year)

# Закрытие соединения
conn.close()

Общее количество записей:

   COUNT(*)
0      7340

Средняя дневная доходность:

   AVG(Daily_Return)
0            0.04717

Сумма дневной доходности за 2022 год:

   SUM(Daily_Return)
0               5.22

Количество дней с положительной доходностью:

   COUNT(*)
0      3697

Средняя дневная доходность по годам:

    Year  AVG(Daily_Return)
0   1996           0.495526
1   1997           0.091138
2   1998           0.141673
3   1999          -0.003241
4   2000          -0.186375
5   2001           0.088279
6   2002          -0.144980
7   2003           0.141897
8   2004           0.010545
9   2005           0.107121
10  2006           0.058498
11  2007           0.167262
12  2008          -0.270478
13  2009           0.193622
14  2010           0.141055
15  2011          -0.108516
16  2012           0.119881
17  2013           0.204087
18  2014           0.061905
19  2015           0.078261
20  2016           0.004627
21  2017           0.025794
22  2018          -0.137251
23  2019           0.073984
24  2020           0.142480
25  2021           0.156627
26  2022           0.021220
27  2023           0.046220
28  2024          -0.020240
29  2025           0.099698
30  2026          -0.173333